{% set name = "pyslim" %}
{% set version = "0.600" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b02a84082a8dfbd2aaac396604f076a405baf4e8da71d2793733d8b1d48cc7e4

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - attrs
    - kastore
    - msprime >=0.7.0
    - numpy
    - tskit

test:
  imports:
    - pyslim

about:
  home: https://github.com/tskit-dev/pyslim
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Tools for dealing with tree sequences coming to and from SLiM.
  description: |
    pyslim is a python module to allow reading and writing of SLiM-produced tree
    sequences as a thin interface to tskit. 
  doc_url: https://pyslim.readthedocs.io/en/latest/
  dev_url: https://pyslim.readthedocs.io/en/latest/development.html

extra:
  recipe-maintainers:
    - winni2k
    - jeromekelleher
    - petrelharp
